/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:30:13 GMT 2019
 */

package sortpom.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sortpom.exception.FailureException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FailureException_ESTest extends FailureException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FailureException failureException0 = new FailureException("_?0d");
      FailureException failureException1 = new FailureException("_?0d", failureException0);
      assertFalse(failureException1.equals((Object)failureException0));
  }
}
